# Generated by Django 3.0.5 on 2020-04-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.IntegerField(choices=[(0, 'Pies'), (1, 'Kot'), (2, 'Inny')], default=2)),
                ('race', models.CharField(max_length=128)),
                ('picture_link', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('date_since', models.DateField(null=True)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=128)),
                ('subject', models.CharField(max_length=128)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.IntegerField(choices=[(0, 'Pies'), (1, 'Kot'), (2, 'Inny')], default=2)),
                ('race', models.CharField(max_length=128)),
                ('picture_link', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Awaiting'), (1, 'Accepted'), (2, 'Declined')], default=0)),
            ],
        ),
    ]
