# Generated by Django 3.0.5 on 2020-04-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unread'), (1, 'Read'), (2, 'Responded')], default=0),
        ),
    ]
