# Generated by Django 3.0.5 on 2020-04-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.CharField(choices=[('dog', 'Pies'), ('cat', 'Kot'), ('other', 'Inny')], default='other', max_length=16),
        ),
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='type',
            field=models.IntegerField(choices=[('dog', 'Pies'), ('cat', 'Kot'), ('other', 'Inny')], default=2),
        ),
    ]
