# Generated by Django 3.0.5 on 2020-04-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_auto_20200417_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=models.ImageField(null=True, upload_to='animals'),
        ),
    ]
