# Generated by Django 3.0.5 on 2020-04-17 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0004_animal_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='filename',
        ),
    ]
