# Generated by Django 3.0.5 on 2020-04-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0005_remove_animal_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='filename',
        ),
        migrations.AddField(
            model_name='submission',
            name='photo',
            field=models.ImageField(null=True, upload_to='submissions'),
        ),
    ]
