# Generated by Django 3.0.5 on 2020-04-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0007_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='type',
            field=models.CharField(choices=[('dog', 'Pies'), ('cat', 'Kot'), ('other', 'Inny')], default='other', max_length=16),
        ),
    ]
